services:
  sac-app:
    image: sac-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sac-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - sac-network
    volumes:
      - sac-app-volume:/storage

  mysql:
    image: mysql:latest
    container_name: sac-mysql-container
    ports:
      - "3306:3306"
    networks:
      - sac-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - sac-mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <root_password>
      MYSQL_DATABASE: db_cit
      MYSQL_USER: cituser
      MYSQL_PASSWORD: <cituser_password>
networks:
  sac-network:
volumes:
  sac-mysql-volume:
  sac-app-volume:
  